### ISSUE TITLE
Cashing not working properly for running same notebook with different params

### ISSUE THREAD

**Issue by julcsii** [minodes/pynb#5] opened 2018-03-13 11:28 UTC
When running a notebook with a set of parameters and then rerunning it with some of the parameters changed, the output of the notebook cells is not updated.

**Comment by elehcimd** [comment] 2018-10-18 12:43
I was not able to reproduce the error.  Therefore, closing the ticket. If the issue appears again, please provide instructions to reproduce it.

**Closed as completed by elehcimd** 2018-10-18 12:43 UTC
